### ISSUE TITLE
LOGIC: Edit job detail

### ISSUE THREAD

**Issue by tuannm99** [tuannm99/RMS#5]
![Screenshot_2022-03-03-08-03-04_1366x768](https://user-images.githubusercontent.com/81021902/156570308-4cf8297f-9fd9-42b6-899a-8eb4b9f394cb.png)
![Screenshot_2022-03-03-08-04-34_1366x768](https://user-images.githubusercontent.com/81021902/156570317-85727b5b-368c-4911-b894-83520a482bab.png)
![Screenshot_2022-03-03-08-04-41_1366x768](https://user-images.githubusercontent.com/81021902/156570326-6836ffa5-2fac-487a-b712-6d05dd47d3d9.png)

**Comment by tuannm99** [comment]
Job Description data bị mất khi save

**Comment by Vietnh21** [comment]
Đã fix
