### ISSUE TITLE
Sửa đường dẫn

### ISSUE THREAD

**Issue by MinhVu0203** [tuannm99/RMS#75]
Xem thông tin của Employee khác vẫn vào Phạm Nguyen
![Uploading 2022-04-08.png…]()
![2022-04-08 (1)](https://user-images.githubusercontent.com/91204734/162388040-7df767a5-e4d2-4555-8037-55e26637e57b.png)

**Comment by tuannm99** [comment]
chi admin moi dc xem thoi nhe
